- hosts: all
  become: yes
  gather_facts: false

  tasks:
  - name: Install packages
    remote_user: ubuntu
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  - name: Add Docker s official GPG key
    remote_user: ubuntu
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Verify that we have the key with the fingerprint
    remote_user: ubuntu
    apt_key:
      id: 0EBFCD88
      state: present

  - name: Set up the stable repository
    remote_user: ubuntu
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
      state: present
      update_cache: yes


  - name: Update apt packages
    remote_user: ubuntu
    apt:
      update_cache: yes
    tags:
      - docker

  - name: Install docker
    remote_user: ubuntu
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - docker-ce
      - docker-compose

  - name: Add remote "ubuntu" user to "docker" group
    remote_user: ubuntu
    user:
      name: "ubuntu"
      groups: "docker"
      append: yes

- hosts: manager
  gather_facts: false

  tasks:
  - name: Init a new swarm with default parameters
    community.docker.docker_swarm:
      state: present
# тут бы придумать, как красиво добавлять воркеры в кластер, иначе руками (:

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: docker-compose.yml
      dest: /home/ubuntu/socks-shop

  - name: Start project from Docker file
    ansible.builtin.command: cd /home/ubuntu/socks-shop && docker-compose up -d
